# _config.yml
title: Bryan Garcia Rodriguez
name: Bryan Garcia Rodriguez
description: "Robotics Research Engineer | Computer Vision & ML | Sustainable Automation"
email: bryan.garcia.b9r@gmail.com
github_username: tnzr
linkedin_username: bryan-garcia-rodriguez-b2803b186
url: "https://tnzr.github.io"
baseurl: ""

# Theme (minimal-mistakes)
remote_theme: mmistakes/minimal-mistakes

  # _config.yml
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - docs
  - test
  - scripts
  - tools
  - .github
  - .sass-cache
  - CHANGELOG
  - LICENSE
  - README
  - _config.yml
  - package.json
  - yarn.lock
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - assets/bower.json

include:
  - _pages

# Minimal Mistakes settings
minimal_mistakes_skin: default
layout: single
author_profile: true


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/
  research:
    output: true
    permalink: /research/:title/

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from


# Navigation
navigation:
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "Projects"
    url: /projects/
  - title: "Blog (Coming)"
    url: /blog/

# Social
social:
  - name: GitHub
    icon: "fab fa-github"
    url: https://github.com/tnzr
  - name: LinkedIn
    icon: "fab fa-linkedin"
    url: https://linkedin.com/in/bryan-garcia-rodriguez-b2803b186
  - name: Email
    icon: "far fa-envelope"
    url: mailto:bryan.garcia.b9r@gmail.com
  - name: IEEE
    icon: "fab fa-leanpub"
    url: https://ieeexplore.ieee.org/author/534813212579107

